var strVar = "";
strVar += "<!--";
strVar += "  Shown, when asking for help.";
strVar += "  Thank you vimium!";
strVar += "-->";
strVar += "<div id=\"HelpDialog\">";
strVar += "  <style>";
strVar += "    #HelpDialog * {";
strVar += "      font-size:11px;";
strVar += "      line-height:130%;";
strVar += "      color:black;";
strVar += "      background-color:white;";
strVar += "    }";
strVar += "    ";
strVar += "    #HelpDialog {";
strVar += "      text-align:left;";
strVar += "      border:3px solid red;";
strVar += "      background-color:white;";
strVar += "      position:fixed;";
strVar += "      width:600px;";
strVar += "      font-family:helvetica, arial, sans;";
strVar += "      border:6px solid #efefef;";
strVar += "      border-radius:12px;";
strVar += "      padding:8px 12px;";
strVar += "      width:640px;";
strVar += "      left:50%;";
strVar += "      \/* This needs to be 1\/2 width to horizontally center the help dialog *\/";
strVar += "      margin-left:-320px;";
strVar += "      top:50px;";
strVar += "      -webkit-box-shadow: rgba(0, 0, 0, 0.4) 0px 0px 6px;";
strVar += "      z-index:99999998;";
strVar += "    }";
strVar += "    ";
strVar += "    #HelpDialog a { color:red; }";
strVar += "    #title, #title * { font-size:20px; }";
strVar += "    .column {";
strVar += "      width:50%;";
strVar += "      float:left;";
strVar += "    }";
strVar += "    ";
strVar += "    .column table, .column td, .column tr { padding:0; margin:0; }";
strVar += "    .column table { width:100%; table-layout:auto; }";
strVar += "    .column td { vertical-align:top; padding:1px; }";
strVar += "    #HelpDialog .column tr > td:first-of-type {";
strVar += "      text-align:right;";
strVar += "      font-weight:bold;";
strVar += "      color:#2f508e;";
strVar += "      white-space:nowrap;";
strVar += "    }";
strVar += "    ";
strVar += "    \/* Make the description column as wide as it can be. *\/";
strVar += "    #HelpDialog .column tr > td:nth-of-type(3) { width:100%; }";
strVar += "    #HelpDialog .divider {";
strVar += "      height:1px;";
strVar += "      width:92%;";
strVar += "      margin:10px auto;";
strVar += "      background-color:#9a9a9a;";
strVar += "    }";
strVar += "    ";
strVar += "    #HelpDialog .sectionTitle {";
strVar += "      font-weight:bold;";
strVar += "      padding-top:3px;";
strVar += "    }";
strVar += "    ";
strVar += "    #HelpDialog .commandName { font-family:\"courier new\"; }";
strVar += "";
strVar += "    #HelpDialog .close {";
strVar += "      position:absolute;";
strVar += "      right:10px;";
strVar += "      top:5px;";
strVar += "      font-family:\"courier new\";";
strVar += "      font-weight:bold;";
strVar += "      color:#990000;";
strVar += "      text-decoration:none;";
strVar += "      padding-left:10px;";
strVar += "      font-size:16px;";
strVar += "    }";
strVar += "";
strVar += "    #HelpDialog .closeButton:hover {";
strVar += "      color:black;";
strVar += "      cursor:default;";
strVar += "      text-decoration:none;";
strVar += "      -webkit-user-select:none;";
strVar += "    }";
strVar += "    ";
strVar += "    #HelpDialogFooter { position: relative; }";
strVar += "    #HelpDialogFooter * { font-size:10px; }";
strVar += "  <\/style>";
strVar += "";
strVar += "  <a class=\"close\" href=\"#\">X<\/a>";
strVar += "  <div id=\"title\">Vim<span style=\"color:red\">Opera<\/span>tor<\/div>";
strVar += "  <div class=\"column\">";
strVar += "    <table>";
strVar += "      <tr><td><\/td><td><\/td><td class=\"sectionTitle\">Navigating the page<\/td><\/tr>";
strVar += "      {{pageNavigation}}";
strVar += "    <\/table>";
strVar += "  <\/div>";
strVar += "  <div class=\"column\">";
strVar += "    <table>";
strVar += "      <tr><td><\/td><td><\/td><td class=\"sectionTitle\">Using find<\/td><\/tr>";
strVar += "      {{findCommands}}";
strVar += "      <tr><td><\/td><td><\/td><td class=\"sectionTitle\">Navigating history<\/td><\/tr>";
strVar += "      {{historyNavigation}}";
strVar += "      <tr><td><\/td><td><\/td><td class=\"sectionTitle\">Manipulating tabs<\/td><\/tr>";
strVar += "      {{tabManipulation}}";
strVar += "      <tr><td><\/td><td><\/td><td class=\"sectionTitle\">Miscellaneous<\/td><\/tr>";
strVar += "      {{misc}}";
strVar += "    <\/table>";
strVar += "  <\/div>";
strVar += "";
strVar += "  <br clear=\"both\"\/>";
strVar += "  <div class=\"divider\"><\/div>";
strVar += "";
strVar += "  <div id=\"HelpDialogFooter\">";
strVar += "    <div class=\"column\">";
strVar += "        <a href=#TOCOME target=\"_blank\">Feedback, Comments?<\/a>";
strVar += "<!--        Kudos to the guys from <a href=http:\/\/github.com\/philc\/vimium\" href=\"_blank\">vimium<\/a> for the inspiration and linkhinting!";
strVar += "-->";
strVar += "    <\/div>";
strVar += "    <div class=\"column\" style=\"text-align:right\">";
strVar += "      <span>Version 0.1<\/span><br\/>";
strVar += "    <\/div>";
strVar += "  <\/div>";
strVar += "<\/div>";
strVar += "";